apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv
  labels:
    storage: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/pvlocal"
  storageClassName: giropops
