apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv-nfs
  labels:
    storage: nfs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.10
    path: "/mnt/nfs" 
  storageClassName: giropops
