apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: meu-pvc-local
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: meu-pvc-local
    persistentVolumeClaim:
      claimName: meu-pvc-local
