apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv
  labels:
    storage: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/testesk8s/local"
  storageClassName: giropops
