apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nginx-daemonset
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx-daemonset
  template:
    metadata:
      labels:
        app: nginx-daemonset
    spec:
      containers:
      - image: nginx:1.14
        name: nginx-daemonset
        resources:
          limits:
            memory: 128Mi
            cpu: 0.3
          requests:
            memory: 64Mi
            cpu: 0.1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
