apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.16.1
        name: nginx
        resources:
          limits:
            memory: 128Mi
            cpu: 0.3
          requests:
            memory: 64Mi
            cpu: 0.1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
