apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    service: webserver
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:  
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx
        name: nginx-deployment
        volumeMounts:
        - mountPath: /giropops
          name: primeiro-emptydir
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.2"
            memory: "64Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: primeiro-emptydir
        emptyDir:
          sizeLimit: "64Mi"
