apiVersion: v1
data:
  nginx.conf: "events {}\n\nhttp {\n  server {\n    listen 80;\n    listen 443 ssl;\n\n
    \   ssl_certicate /etc/nginx/tls/nginx.crt;\n    ssl_certicate_key /etc/nginx/tls/nginx.key;\n\n
    \   location / {\n      return 200 'Bem-vindo ao Nginx!\\n';\n      add_header
    Content-Type text/plain;\n    }\n  }\t  \n}\n"
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
