apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    env: dev
spec:
  selector:
    app: nginx
  ports:
  - port: 443
    name: http
    targetPort: 443
    nodePort: 32400
  type: NodePort
